name: ConPyguration ci

on:
  pull_request:
    branches: ["*"]

jobs:
  Tests:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel
          pip install poetry
          poetry config virtualenvs.create false
          python -m poetry install
          pip install pytest pytest-xdist
        shell: bash

      - name: Check environment
        run: |
          python --version
          pip --version
          pip list

      - name: Run Pytest tests
        run: python -m pytest tests/ -n 4 -v
        shell: bash
